import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { authenticateRequest, unauthorizedResponse, forbiddenResponse } from '@/lib/auth'
import { getTenantContext } from '@/lib/tenant'
import ExcelJS from 'exceljs'

// GET /api/reports/monthly/export/[id] - Export employee's own report as Excel workbook
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const payload = await authenticateRequest(request)
    if (!payload) return unauthorizedResponse()
    const tenant = await getTenantContext(payload)
    if (!tenant) return unauthorizedResponse('Active organization membership required')

    const { id } = await params

    const report = await db.reportingMonthlyReport.findFirst({
      where: { id, organizationId: tenant.organizationId },
      include: { employee: { include: { membership: true, position: true } } },
    })

    if (!report) {
      return NextResponse.json({ error: 'Report not found' }, { status: 404 })
    }

    // Ownership check: employee can only export their own reports
    if (payload.role === 'employee' && report.employee.membership.userId !== payload.userId) {
      return forbiddenResponse('You can only export your own reports')
    }

    const d = report.reportData as Record<string, any>
    const info = d.employeeInfo
    const stats = d.statistics
    const BRANDED = 'FF0B1F6D'
    const GREEN = 'FF059669'
    const styleHeader = (row: ExcelJS.Row, color: string) => {
      row.font = { bold: true, color: { argb: 'FFFFFFFF' } }
      row.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: color } }
    }

    const wb = new ExcelJS.Workbook()
    wb.creator = 'NIWMS Report Intelligence Engine v2.0'
    wb.created = new Date()

    // ══════════════════════════════════════════════════════════════
    // SHEET 1: SUMMARY (Employee Info + Executive Summary + Overview)
    // ══════════════════════════════════════════════════════════════
    const s1 = wb.addWorksheet('Summary')
    s1.columns = [{ header: 'Field', key: 'f', width: 30 }, { header: 'Details', key: 'd', width: 65 }]

    const summaryRows = [
      { f: 'NIWMS MONTHLY REPORT', d: '' },
      { f: '────────────────────────', d: '' },
      { f: '', d: '' },
      { f: 'EMPLOYEE INFORMATION', d: '' },
      { f: 'Employee Name', d: info.name },
      { f: 'Employee ID', d: info.employeeId },
      { f: 'Position', d: info.position },
      { f: 'Reporting Period', d: info.reportingMonthLabel },
      { f: '', d: '' },
      { f: 'REPORT METRICS', d: '' },
      { f: 'Status', d: report.status.charAt(0).toUpperCase() + report.status.slice(1) },
      { f: 'Generated On', d: report.createdAt.toISOString() },
      { f: 'Engine Version', d: d.engineVersion || '2.0.0' },
      { f: 'Generated By', d: report.generatedByUserId === payload.userId ? 'Employee (Self)' : 'Administrator' },
      { f: '', d: '' },
      { f: 'EXECUTIVE SUMMARY', d: '' },
      { f: 'Summary', d: d.summary },
      { f: 'Dominant Focus', d: d.dominantFocus || 'N/A' },
      { f: '', d: '' },
      { f: 'KEY WORK AREAS', d: '' },
      ...(d.keyWorkAreas || []).map((area: string, i: number) => ({
        f: `  ${i + 1}.`,
        d: area,
      })),
    ]

    for (const row of summaryRows) s1.addRow(row)
    styleHeader(s1.getRow(1), BRANDED)
    s1.getRow(4).font = { bold: true, size: 11 }
    s1.getRow(12).font = { bold: true, size: 11 }
    s1.getRow(17).font = { bold: true, size: 11 }
    s1.getRow(20).font = { bold: true, size: 11 }
    s1.eachRow((row, rn) => {
      if (rn > 1 && row.getCell(1).value) row.getCell(1).font = { bold: true }
    })

    // ══════════════════════════════════════════════════════════════
    // SHEET 2: STATISTICS (Activity + Submission stats)
    // ══════════════════════════════════════════════════════════════
    const s2 = wb.addWorksheet('Statistics')
    s2.columns = [{ header: 'Metric', key: 'm', width: 35 }, { header: 'Value', key: 'v', width: 25 }]

    const statRows = [
      { m: 'SUBMISSION STATISTICS', v: '' },
      { m: 'Total Reports Submitted', v: `${stats.totalReportsSubmitted}` },
      { m: 'Expected Working Days', v: `${stats.expectedReports}` },
      { m: 'Submission Rate', v: `${stats.submissionRate}%` },
      { m: 'Missed Submissions', v: `${stats.missedSubmissions}` },
      { m: 'Longest Streak', v: `${stats.longestStreak} days` },
      { m: 'Current Streak', v: `${stats.currentStreak} days` },
      { m: '', v: '' },
      { m: 'ACTIVITY STATISTICS', v: '' },
      { m: 'Total Activities Recorded', v: `${stats.totalActivities}` },
      { m: 'Avg Activities Per Day', v: `${stats.avgActivitiesPerDay}` },
      { m: 'Avg Words Per Report', v: `${stats.avgWordsPerReport}` },
      { m: 'Total Words Written', v: `${stats.totalWords}` },
      { m: '', v: '' },
      { m: 'TEMPORAL ANALYSIS', v: '' },
      { m: 'Most Active Day', v: `${stats.mostActiveDay || 'N/A'} (${stats.mostActiveDayCount} reports)` },
      { m: 'Most Active Week', v: `${stats.mostActiveWeek || 'N/A'} (${stats.mostActiveWeekCount} activities)` },
      { m: '', v: '' },
      { m: 'CATEGORY ANALYSIS', v: '' },
      { m: 'Categories Worked', v: `${stats.categoriesWorked}` },
      { m: 'Top Category', v: stats.topCategory },
      { m: 'Most Frequent Category', v: stats.mostFrequentCategory },
      ...(stats.top3Categories || []).map((c: { name: string; count: number; percentage: number }) => ({
        m: `  → ${c.name}`,
        v: `${c.count} activities (${c.percentage}%)`,
      })),
    ]

    for (const row of statRows) s2.addRow(row)
    styleHeader(s2.getRow(1), BRANDED)
    s2.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } }
    s2.getRow(9).font = { bold: true, size: 11 }
    s2.getRow(16).font = { bold: true, size: 11 }
    s2.getRow(20).font = { bold: true, size: 11 }
    s2.eachRow((row, rn) => {
      if (rn > 1 && row.getCell(1).value) row.getCell(1).font = { bold: true }
    })

    // ══════════════════════════════════════════════════════════════
    // SHEET 3: ACTIVITIES (Timeline with full details)
    // ══════════════════════════════════════════════════════════════
    const s3 = wb.addWorksheet('Activities')
    s3.columns = [
      { header: 'Date', key: 'date', width: 16 },
      { header: 'Time In', key: 'timeIn', width: 10 },
      { header: 'Time Out', key: 'timeOut', width: 10 },
      { header: 'Activity Description', key: 'activity', width: 60 },
      { header: 'Category', key: 'category', width: 22 },
      { header: 'Location', key: 'location', width: 25 },
      { header: 'Comments / Notes', key: 'comments', width: 40 },
    ]

    const timeline = d.activityTimeline || []
    for (const entry of timeline) {
      // One row per date with all activities joined
      s3.addRow({
        date: entry.dateLabel,
        timeIn: entry.timeIn || '',
        timeOut: entry.timeOut || '',
        activity: entry.activities.join('\n'),
        category: entry.primaryCategory,
        location: entry.location || '',
        comments: entry.comments || '',
      })
    }

    styleHeader(s3.getRow(1), GREEN)

    // Add alternating row colors for readability
    s3.eachRow((row, rowNumber) => {
      if (rowNumber > 1 && rowNumber % 2 === 0) {
        row.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFF8F9FC' },
        }
      }
    })

    // ══════════════════════════════════════════════════════════════
    // SHEET 4: ACHIEVEMENTS
    // ══════════════════════════════════════════════════════════════
    const s4 = wb.addWorksheet('Achievements')
    s4.columns = [
      { header: '#', key: 'num', width: 5 },
      { header: 'Achievement', key: 'achievement', width: 80 },
      { header: 'Source', key: 'source', width: 25 },
    ]

    const achievements = d.achievements || []
    for (let i = 0; i < achievements.length; i++) {
      s4.addRow({
        num: i + 1,
        achievement: achievements[i],
        source: 'Employee Daily Reports',
      })
    }

    styleHeader(s4.getRow(1), GREEN)

    // ══════════════════════════════════════════════════════════════
    // SHEET 5: MANAGER NOTES + APPROVAL
    // ══════════════════════════════════════════════════════════════
    const s5 = wb.addWorksheet('Manager Notes')
    s5.columns = [{ header: 'Section', key: 'section', width: 30 }, { header: 'Content', key: 'content', width: 70 }]

    s5.addRow({ section: 'MANAGER COMMENTS', content: '' })
    s5.addRow({ section: 'Overall Assessment', content: '' })
    s5.addRow({ section: 'Strengths', content: '' })
    s5.addRow({ section: 'Areas for Improvement', content: '' })
    s5.addRow({ section: 'Recommendations', content: '' })
    s5.addRow({ section: '', content: '' })
    s5.addRow({ section: 'PERFORMANCE RATING', content: '' })
    s5.addRow({ section: 'Rating (1-5)', content: '' })
    s5.addRow({ section: '', content: '' })
    s5.addRow({ section: 'APPROVAL', content: '' })
    s5.addRow({ section: 'Approved By', content: '' })
    s5.addRow({ section: 'Approval Date', content: '' })
    s5.addRow({ section: 'Signature', content: '' })
    s5.addRow({ section: '', content: '' })
    s5.addRow({ section: 'Report Metadata', content: `Generated: ${report.createdAt.toISOString()}` })
    s5.addRow({ section: '', content: `Engine: NIWMS Report Intelligence Engine v${d.engineVersion || '2.0.0'}` })
    s5.addRow({ section: '', content: `This report was generated automatically from daily activity submissions.` })

    styleHeader(s5.getRow(1), BRANDED)
    s5.getRow(8).font = { bold: true, size: 11 }
    s5.getRow(11).font = { bold: true, size: 11 }

    // ──── EXPORT ────
    const buffer = await wb.xlsx.writeBuffer()

    const filename = `NIWMS-Monthly-Report-${info.employeeId}-${info.reportingMonth}.xlsx`

    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    })
  } catch (error) {
    console.error('Export monthly report error:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
